spring.application.name=ecommerce
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Akash@8433

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true